### PR TITLE
add endpoint for token validation

### PR DESCRIPTION
**Pull request by AntonioLok**
# Description

This PR implements the follow:
1 - Add a route to validate if a token sent from the front-end is still valid. If the token is valid, the decoded token will be sent with a http status code 200 as response. If either the token is malformed, expired or the signature is invalid, a status code of 401 (unathorized) will be sent to as response. 

# Test
1 - Install dependencies `npm i`. 
2 - Set the required environment variable `JWT_SECRET` by creating a `.env` file in the main directory and set your secret in that file ie. `JWT_SECRET=HELLO`.
3 - run the app using `npm run start`. If you want to skip step 2, you can set the env with `JWT_SECRET=HELLO npm run start`.

- Login with your credentials (if you do not remember your credential, you can use my credential from the sample command:
    -  method: POST http://localhost:8000/users/login
    -  body parameters:
        - `email` type: string
        - `password` type: string

Sample command:
`curl -d "email=antonio@gmail.coml&password=password" -X POST http://localhost:8000/users/login`

The response should be :

```
{"statusCode":200,"statusText":"SUCCESS","data":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFudG9uaW9AZ21haWwuY29tbCIsImlhdCI6MTU2Nzk2Mzg2OSwiZXhwIjoxNTY4MDUwMjY5fQ.VQBz0Ci5ywZr5CRZQG1SfUwtdWPeamC3HbW5z_rEGJY"}
```
Note that the token was sent in the data field.

Now we can proceed to test our new endpoint!

- Check if the token is valid by using our new endpoint:
    -  method: GET http://localhost:8000/users/validate-token/:token
    -  body parameters: none
:token will be the same token that you received from the login response. In this case for me, :token will be `eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFudG9uaW9AZ21haWwuY29tbCIsImlhdCI6MTU2Nzk2Mzg2OSwiZXhwIjoxNTY4MDUwMjY5fQ.VQBz0Ci5ywZr5CRZQG1SfUwtdWPeamC3HbW5z_rEGJY`

Sample command:
`curl -X GET http://localhost:8000/users/validate-token/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFudG9uaW9AZ21haWwuY29tbCIsImlhdCI6MTU2Nzk2Mzg2OSwiZXhwIjoxNTY4MDUwMjY5fQ.VQBz0Ci5ywZr5CRZQG1SfUwtdWPeamC3HbW5z_rEGJY`

The response should be: 

```
{"statusCode":200,"statusText":"SUCCESS","data":{"id":"antonio@gmail.coml","iat":1567963869,"exp":1568050269}}
```

To test for if the token is malformed, we will send a malformed token:
`curl -X GET http://localhost:8000/users/validate-token/malformed-token`

The response should be:

```
{"statusCode":401,"statusText":"UNAUTHORIZED","message":"The token received is malformed"}

```

To test for if the token is expired, we will send an expired token (I created this token with a 1s exp time to test this part):

`curl -X GET http://localhost:8000/users/validate-token/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InRlc3QiLCJpYXQiOjE1Njc5NjIxMTYsImV4cCI6MTU2Nzk2MjExN30.YZ5x1b6xRYYsK3Dn2bCCLjSgXTlHJ6C7oJdnWZYWhBM`

The response should be:

```
{"statusCode":401,"statusText":"UNAUTHORIZED","message":"The token received has expired"}

```

To test for if the token has an invalid signature, we will send a token that has an invalid signature:

`curl -X GET http://localhost:8000/users/validate-token/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InRlc3QiLCJpYXQiOjE1Njc5NjIxMTYsImV4cCI6MTU2Nzk2MjExN30.YZ5x1b6xRYYsK3Dn2bCCLjSgXTlHJ6C7oJdnWZYWhBMs`

The response should be:

```
{"statusCode":401,"statusText":"UNAUTHORIZED","message":"The token received has an invalid signature"}
```

# Next to do
Front end implementation which will make use of this endpoint to check if the current token stored in the local storage is valid or not.

### CODE REVIEW

**Comment by howardhenry** [comment]
It's a good initiative to validate the token. However, I don't think there needs to be an endpoint that does this. If the frontend validates the token before every request, then you've now doubled the number of requests in the application. Instead, include a middleware on the backend that intercepts every request and validates it before passing it to the controller. If the token is malformed, expired or in any other way invalid, you can return status 401 to the frontend.

Was there a specific use-case you were trying to address by including this endpoint?

**Comment by AntonioLok** [comment]
> It's a good initiative to validate the token. However, I don't think there needs to be an endpoint that does this. If the frontend validates the token before every request, then you've now doubled the number of requests in the application. Instead, include a middleware on the backend that intercepts every request and validates it before passing it to the controller. If the token is malformed, expired or in any other way invalid, you can return status 401 to the frontend.
> 
> Was there a specific use-case you were trying to address by including this endpoint?

Yes! I was working on the front-end part which will make use of this end-point. I will be opening the PR in the next hour or so.

But just to explain why I created this endpoint, it's because:
I need a way to know if the user is logged in to display the `log out` button and not render the `log in` button. How I planned to do that initially was to check if there's a token. So something like `isAuthenticated = !!localStorage.getItem('OS_AUTH_TOKEN')`. However this only checks if there's an item for the `OS_AUTH_TOKEN`. It does not check if that item (token) is valid which is why I created this end-point which I plan on calling to check if that item is a valid token, and if it is, display the logout button.

This will be more clear on my upcoming PR!

**Comment by howardhenry** [comment]
> > It's a good initiative to validate the token. However, I don't think there needs to be an endpoint that does this. If the frontend validates the token before every request, then you've now doubled the number of requests in the application. Instead, include a middleware on the backend that intercepts every request and validates it before passing it to the controller. If the token is malformed, expired or in any other way invalid, you can return status 401 to the frontend.
> > Was there a specific use-case you were trying to address by including this endpoint?
> 
> Yes! I was working on the front-end part which will make use of this end-point. I will be opening the PR in the next hour or so.
> 
> But just to explain why I created this endpoint, it's because:
> I need a way to know if the user is logged in to display the `log out` button and not render the `log in` button. How I planned to do that initially was to check if there's a token. So something like `isAuthenticated = !!localStorage.getItem('OS_AUTH_TOKEN')`. However this only checks if there's an item for the `OS_AUTH_TOKEN`. It does not check if that item (token) is valid which is why I created this end-point which I plan on calling to check if that item is a valid token, and if it is, display the logout button.
> 
> This will be more clear on my upcoming PR!

Gotcha! So, there are two ways a token can be invalid:
1. The token expires
- You can already check the expiration of a token client-side by decoding the JWT token and referencing the `exp` property. And, you don't need the token secret to do that. Check out https://npmjs.com/package/jwt-decode.

2. The token was tampered with by the user on his/her own machine
- There is no need to create any feature for addressing the second method as your application should not support handling a good UX flow for someone who is hacking. The backend can use a middleware to validate if the token has been tampered with and reject the token with a `401` in that case. The backend should also check for token expiration, just in case the frontend fails this check.

**Comment by AntonioLok** [comment]
> > > It's a good initiative to validate the token. However, I don't think there needs to be an endpoint that does this. If the frontend validates the token before every request, then you've now doubled the number of requests in the application. Instead, include a middleware on the backend that intercepts every request and validates it before passing it to the controller. If the token is malformed, expired or in any other way invalid, you can return status 401 to the frontend.
> > > Was there a specific use-case you were trying to address by including this endpoint?
> > 
> > 
> > Yes! I was working on the front-end part which will make use of this end-point. I will be opening the PR in the next hour or so.
> > But just to explain why I created this endpoint, it's because:
> > I need a way to know if the user is logged in to display the `log out` button and not render the `log in` button. How I planned to do that initially was to check if there's a token. So something like `isAuthenticated = !!localStorage.getItem('OS_AUTH_TOKEN')`. However this only checks if there's an item for the `OS_AUTH_TOKEN`. It does not check if that item (token) is valid which is why I created this end-point which I plan on calling to check if that item is a valid token, and if it is, display the logout button.
> > This will be more clear on my upcoming PR!
> 
> Gotcha! So, there are two ways a token can be invalid:
> 
> 1. The token expires
> 
> * You can already check the expiration of a token client-side by decoding the JWT token and referencing the `exp` property. And, you don't need the token secret to do that. Check out https://npmjs.com/package/jwt-decode.
> 
> 1. The token was tampered with by the user on his/her own machine
> 
> * There is no need to create any feature for addressing the second method as your application should not support handling a good UX flow for someone who is hacking. The backend can use a middleware to validate if the token has been tampered with and reject the token with a `401` in that case. The backend should also check for token expiration, just in case the frontend fails this check.

1. WHATTTTT. I didn't know you could just verify the token from the client side like that. I thought you would need to also pass the secret key to a function you were calling to verify. I am kinda confused about this package... I thought they needed to know the secret key in order to decode it.

2. Ah right. That's what I read on many websites but my main concern here is how can I know if the user is logged in or not. I need to know this in order to display the "Logout" button. Do you think checking for if there is a token good enough? Something like:

`const isAuthenticated = !!token;`

Also you mentioned to `check if the token is malformed in a middleware in the backend.`. This should only happen if I want to access any endpoints which requires authentication, correct? Also, If the token in malformed and this is caught on the backend, on the front-end part, is it a good idea to remove this token?

**Comment by howardhenry** [comment]
Yup, you can get the expiration date/time of the token client-side. And, this will tell you if the user is logged in or not. If the user logs out manually, the token would be deleted from the client.

Separately, if the token is malformed OR expired, it should be removed from the frontend.

**Pull request closed without merging**
