### PR TITLE
update-response-status-for-invalid-token

### PR DESCRIPTION
**Pull request by AntonioLok**
# Description

This PR implements the follow:
1 - Update the response status code when the token is invalid. Currently its returning 403 (forbidden) and it should be 401. I've also added custom messages for each type of invalid tokens.

# Test
1 - Install dependencies 
2 - Set the required environment variable `JWT_SECRET` by creating a `.env` file in the main directory and set your secret in that file ie. `JWT_SECRET=HELLO`.
3 - run the app using `npm run start`. If you want to skip step 2, you can set the env with `JWT_SECRET=HELLO npm run start`.

Send a GET request to get the user cart with an invalid token:
-  method: GET http://localhost:8000/carts
-  body parameters: none
-  request header must contain "Authorization: Bearer token"

For this PR, we dont need valid tokens since we are testing for invalid tokens.

Sample commands:
- No token provided:
`curl http://localhost:8000/carts`
Response status should be:
`{"statusCode":401,"statusText":"UNAUTHORIZED","message":"Token was not provided"}`

- Malformed token:
`curl -H "Authorization: Bearer malformed-token" -X GET http://localhost:8000/carts`
Response status should be:
`{"statusCode":401,"statusText":"UNAUTHORIZED","message":"The token received is malformed"}`

- Expired token:
`curl -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InRlc3QiLCJpYXQiOjE1Njc5NjIxMTYsImV4cCI6MTU2Nzk2MjExN30.YZ5x1b6xRYYsK3Dn2bCCLjSgXTlHJ6C7oJdnWZYWhBM" -X GET http://localhost:8000/carts`
Response status should be:
`{"statusCode":401,"statusText":"UNAUTHORIZED","message":"The token received has expired"}`

- Invalid signature:
`curl -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InRlc3QiLCJpYXQiOjE1Njc5NjIxMTYsImV4cCI6MTU2Nzk2MjExN30.YZ5x1b6xRYYsK3Dn2bCCLjSgXTlHJ6C7oJdnWZYWhBMs" -X GET http://localhost:8000/carts`
Response status should be :
`{"statusCode":401,"statusText":"UNAUTHORIZED","message":"The token received has an invalid signature"}`

# To do after
Remove token on the front end when we receive a 401.

### CODE REVIEW

**Comment by AntonioLok** [comment]
> When I run the app and do a get request to /carts (`curl http://localhost:8000/carts`) I get a `500` status code response. There is no useful error in the console. Please fix the code and look about addressing your error handling to improve the ability to debug.

Eh, I did not include a case for when no token was provided in the Authorization request header. Good catch.

"and look about addressing your error handling to improve the ability to debug." Not really sure what you mean here. Are you are suggesting I should implement like an error logger (ie. using winston) to improve the ability to debug?

**Comment by howardhenry** [comment]
Re: logging, yes you should have some sort of message logged to the console when an error occurs in your application. The generic 500 error doesn't tell me where the error originated in the app. The only reason you know where to look is because you wrote it. You have to always write code with the mindset that other developers will be maintaining it. No real application was built by one person alone.

**Comment by AntonioLok** [comment]
> Re: logging, yes you should have some sort of message logged to the console when an error occurs in your application. The generic 500 error doesn't tell me where the error originated in the app. The only reason you know where to look is because you wrote it. You have to always write code with the mindset that other developers will be maintaining it. No real application was built by one person alone.

Just a reminder about what we talked months ago. I recall saying that I would add such functionality (an error logger) in the future. I created a ticket for that in my backlog. Yes, I was planning to work on it but I didnt think it would be a high priority since I am the only one working on this project for the time being and so decided to just do it much later. But given that you think this is a high priority feature, I have opened a PR to add it https://github.com/AntonioLok/online-shopping-reactJS-Backend/pull/14

**Comment by AntonioLok** [comment]
@howardhenry I have updated the PR to include proper message when token is not provided.

**Pull request merged**
